version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APP_TEMPLATE_ID: $VITE_APP_TEMPLATE_ID
        VITE_APP_SERVICE_ID: $VITE_APP_SERVICE_ID
        VITE_APP_PUBLIC_KEY: $VITE_APP_PUBLIC_KEY
        API_TOKEN: $API_TOKEN
    image: myportfolio:latest
    ports:
      - "5000:5000"
    restart: always
    environment:
      VITE_APP_TEMPLATE_ID: $VITE_APP_TEMPLATE_ID
      VITE_APP_SERVICE_ID: $VITE_APP_SERVICE_ID
      VITE_APP_PUBLIC_KEY: $VITE_APP_PUBLIC_KEY
      API_TOKEN: $API_TOKEN
      NODE_ENV: production
