version: "3"

services:
  client:
    build:
      context: client
    ports:
      - 5173:5173
    stdin_open: true
    restart: always
    networks:
      - react-express
  server:
    build:
      context: server
    ports:
      - "5000:5000"
    restart: always
    networks:
      - react-express

networks:
  react-express:
